### ISSUE TITLE
Question About The project

### ISSUE THREAD

**Issue by nonunknown** [samuelbigos/tutorial_projects#2]
Must say this is an awesome project, I would like to know if by any chance this can be archieved on low end computers?

**Comment by samuelbigos** [comment]
Hey nonunknown, thanks! It depends on how low spec you're talking about, and what sacrifices you're willing to make in terms of quality. All of the lighting is calculated on the GPU so it is entirely dependent on that hardware. You should be able to run this project on quite old hardware, though I think it would need GLES3 support (I haven't tested GLES2 though, it might work). 

However when you scale it up to an actual game, things become harder. A game made with this sort of lighting will definitely have higher hardware requirements than other 2D games.

What are you thinking of doing?

**Comment by nonunknown** [comment]
Well I've already tested your project some weeks ago, I have a intel HD Graphics 3000 , intel i3 2.1Ghz 2 Gen, 8 GB Mem. So I'm working on a top-down shooter, and would like to have a more realistic lighting, and run on most hardware as possible. Even if this means some sacrifices on graphics quality in terms of your shader...

**Comment by samuelbigos** [comment]
I wouldn't recommend using an integrated graphics chip with this lighting technique, there's no way you would get acceptable performance unfortunately. I would stick to sprite based lighting for your project, sorry!

**Comment by nonunknown** [comment]
Hmm, okay thanks for your time :+1:
